### ISSUE TITLE
feat(alerts/ui): optimization of silence-features in alerts plugin

### ISSUE THREAD

**Issue by TilmanHaupt** [cloudoperators/greenhouse-extensions#152]
Depending on other projects:

- [x] TopNavigation change
- [x] Pipe Props directly to store to get rid of useLayoutEffect and ensure faster rendering

Prometheus Alertmanager API fails on filtering active, pending and expiring silences. So following Tasks are aborted: 
- Just call API for active / expired silences if just a subset is shown.
- Dont fetch to long expired silences

Source: https://github.com/prometheus/alertmanager/issues/2928

**Comment by MartinS-git** [comment]
Changed TopNavigation CSS style with PR
 https://github.com/cloudoperators/juno/pull/129
