### ISSUE TITLE
[kube-monitoring] Define and implement chart test cases

### ISSUE THREAD

**Issue by richardtief** [cloudoperators/greenhouse-extensions#217]
Define test cases for the [kube-monitoring chart](https://github.com/cloudoperators/greenhouse-extensions/tree/main/kube-monitoring/charts) which is a configured [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md)

### Acceptance Criteria

- [x]  Pods are up and running (prometheus-operator, prometheus, kube-state-metrics-exporter, ...)
- [x]  Persistent volume is created and accessible
- [x]  prometheus-operator and CRDs are installed 
- [x]  resouce `kube-minitoring` is present of type `prometheus`
- [x] -  Copy the Dockerfile from the bats-detik repository and place it in this repository `greenhouse-extensions`
- [x] - Create a GitHub Action to publish the dockerimage to this repository's ghcr registry.  https://github.com/cloudoperators/greenhouse-extensions/pull/237
- [x] -  Add Service Account and Role and Rolebinding

**Comment by ibakshay** [comment]
**Sync with Richard - July 18**
- Demo:  bats-detik can be used to do integration test to check if the pod is running

#### Next Steps: 

- Create a Dockerfile and push it to our registry and is ready to be used as `bats-detik` doesn't provice an official docker image.
- Add Service Account and Role and Rolebinding - [take inspiration from here](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/tests/test-role.yaml)

**Comment by ibakshay** [comment]
kube-monitoring PluginDefinition version bump is done seperately in this PR - https://github.com/cloudoperators/greenhouse-extensions/pull/256.
