### ISSUE TITLE
[opentelemetry] production-ready testing OTEL-logs collector

### ISSUE THREAD

**Issue by timojohlo** [cloudoperators/greenhouse-extensions#245]
## Context 
Currently we are running OpenTelemetry with only collecting, processing and forwarding a few logs. We want to test OpenTelemetry with production load data including Daemonset. This should not test a cluster but rather OpenTelemetry itself. 

Expected to be dragged into Sprint 10/24, since observing will take some time.

## Prerequisite

- [ ] [339](https://github.com/cloudoperators/greenhouse-extensions/issues/339)

## Acceptance Criteria 
- [ ] Decide in which cluster to test OpenTelemetry (old landscape)
- [x] Including grok-parsing
- [x] Filter to only parse some logs
- [ ] Convert fluent configs to OpenTelemetry configs

**Comment by timojohlo** [comment]
This issue needs more details that can be or need to be discussed in the observability meeting.

**Comment by Kuckkuck** [comment]
postponed, greenhouse has to deploy more stuff to prod to get our opentelemetry plugin also to prod greenhouse. That this can be deployed to the ceph clusters.

**Comment by Kuckkuck** [comment]
Follow up ticket #407

**Comment by viennaa** [comment]
Ticket is too generic, @Kuckkuck to create follow-up tickets for 10/24 Sprint
