### ISSUE TITLE
[opentelemetry] log parsing for ceph cluster

### ISSUE THREAD

**Issue by timojohlo** [cloudoperators/greenhouse-extensions#311]
## Context 
Administrators (such as Ceph) want also to provide a custom config for OpenTelemetry Collectors. We want to provide a way for users to upload or link the necessary config values that should be included.

## Acceptance Criteria 
- [x] Define requirements for log parsing
- [ ] Decide structure/architecture to allow custom configs to be included in PluginDefinition
- [ ] Test/verify that custom config values are valid

**Comment by Kuckkuck** [comment]
Ceph log parsing was added with 
[pull request 348](https://github.com/cloudoperators/greenhouse-extensions/pull/348)

**Comment by Kuckkuck** [comment]
Follow up ticker #408

**Comment by viennaa** [comment]
Open tasks need to be moved in dedicated tickets @Kuckkuck
