### ISSUE TITLE
[opentelemetry] add labels according to naming convention

### ISSUE THREAD

**Issue by timojohlo** [cloudoperators/greenhouse-extensions#338]
## Context 
In a future version of OpenTelemtry we want to provide extended labels that describe each log-line based on source, host, environment etc. 

## Acceptance Criteria 
- [x] Discuss and align on best-pratice labeling
- [x] Implement labeling/attributes for each source (k8s events, container logs, journal logs etc.) where possible
- [x] Document label-approach

## References
https://opentelemetry.io/docs/specs/semconv/resource/

## Example
Attributes are grouped logically by the type of the concept that they described. Attributes in the same group have a common prefix that ends with a dot. For example all attributes that describe Kubernetes properties start with “k8s.”

**Comment by Kuckkuck** [comment]
Added Kubernetes labels according to [Opentelemetry Kubernetes specs](https://opentelemetry.io/docs/specs/semconv/resource/k8s/).

Pull request [#369 ](https://github.com/cloudoperators/greenhouse-extensions/pull/369)

the following labels are not available:
k8s.container.status.last_terminated_reason
k8s.cronjob.uid
