### ISSUE TITLE
[opentelemetry] Create Plugin

### ISSUE THREAD

**Issue by artherd42** [cloudoperators/greenhouse-extensions#34]
## Context

A platform like Greenhouse supports OpenTelemetry and thus offers a vendor-independent implementation for receiving, processing and exporting telemetry data. The OpenTelemetry Collector eliminates the need to run, operate and maintain multiple agents/collectors. It operates with improved scalability and supports open source observability data formats (e.g. Jaeger, Prometheus, Fluent Bit, etc.), which are sent to one or more open source backends. The local collector agent is the default location where instrumentation libraries export their telemetry data.

## Acceptance criteria

1. **Logs:** Collect sys logs and container logs from a Kubernetes cluster
   - Filter and transform the telemetry data
   - Export the data to an OpenSearch index
2. **Metrics:** R&D inc. [Prometheus project](https://prometheus.io/blog/2024/03/14/commitment-to-opentelemetry/)
3.  **Traces** R&D how to setup a pipeline

## References 

- https://opentelemetry.io/docs/collector
- https://opentelemetry.io/docs/kubernetes/helm/collector/

**Comment by timojohlo** [comment]
Done
Related PRs:
- [opentelemetry-operator] template otel index #227 
- [opentelemetry-operator] init plugin for OpenTelemetry Operator #221
