### ISSUE TITLE
[opentelemetry] Ceph landscapes: logs collector proof to be production ready

### ISSUE THREAD

**Issue by Kuckkuck** [cloudoperators/greenhouse-extensions#353]
### Run in (pre)-production for at least one sprint to get proof for stability and production readiness
- [x] Observe if logs are parsed correctly
- [ ] Observe that no logs are missing
- [ ]  Observe a stable environment over time at least one sprint

## Prerequisite

- [x] [245](https://github.com/cloudoperators/greenhouse-extensions/issues/245)

**Comment by Kuckkuck** [comment]
Landscapes used for testing are the greenhouse ceph cluster st-*.

**Comment by timojohlo** [comment]
contributing via https://github.com/cloudoperators/greenhouse-extensions/pull/478

**Comment by timojohlo** [comment]
Observing of logs will take place this week

**Comment by Kuckkuck** [comment]
Moved the PR for ceph parsing to this PR #511
