### ISSUE TITLE
[EPIC] Create Plutono plugin

### ISSUE THREAD

**Issue by artherd42** [cloudoperators/greenhouse-extensions#38]
## Context 

A platform like Greenhouse should have a tool for visualising dashboards. Currently [Plutono](https://github.com/credativ/plutono) is used as a solution, a fork of [Grafana](https://github.com/grafana/grafana) 7.5.17 under the Apache 2.0 licence, limited to maintenance and security updates.

## Tasks

- [x] (https://github.com/cloudoperators/greenhouse-extensions/issues/273)

**Comment by richardtief** [comment]
The Grafana community helm chart has been transferred to Plutono. Checked out at [appVersion: 7.5.3](https://github.com/grafana/helm-charts/blob/46344fbde884345ce44e13cbc7d689b848ea67d9/charts/grafana/Chart.yaml) as it is the last source before Grafana `v8`.

**Comment by auhlig** [comment]
As discussed with @richardtief via IM: Initially only in remote clusters with pre-configured datasource as part of kube-monitoring plugin.
Document how to provide custom dashboards.

@kengou to work on dashboards provided via [k8s-monitoring](https://github.com/cloudoperators/k8s-monitoring] repository.

More clarification needed on holistic plutono in central cluster. Related [ADR#6](https://github.com/cloudoperators/documentation/pull/1)

**Comment by auhlig** [comment]
Q3 deliverables:
- ([plutono] Initialise the plugin with basic functionality  #273)
- Integration with and auto-discovery of existing Prometheus data sources

**Comment by richardtief** [comment]
Completed. New issues are created for subsequent functions.
