### ISSUE TITLE
[opentelemetry] Roll out OpenTelemetry-collector for logs to Ceph landscapes

### ISSUE THREAD

**Issue by Kuckkuck** [cloudoperators/greenhouse-extensions#408]
### Priority

None

### Is your feature request related to a problem?

- [x] Get cam roles to access st-* ceph cluster for namespace otel to debug OpenTelemetry logs collector
- [ ] Rollout plugin to Greenhouse prod and afterwards to ceph clusters
- [ ] Check ceph grok parsing together with the ceph team

**Comment by timojohlo** [comment]
deployed in ceph cluster via [#7263](https://github.com/sapcc/helm-charts/pull/7263) here: https://github.com/sapcc/helm-charts/blob/master/system/greenhouse-ccloud/templates/opentelemetry-pluginpreset.yaml
