### ISSUE TITLE
[opentelemetry] Enhance monitoring dashboard and add alerts for OpenTelemetry logs

### ISSUE THREAD

**Issue by Kuckkuck** [cloudoperators/greenhouse-extensions#409]
### Priority

None

### Is your feature request related to a problem?

- [x] Enhance monitoring dashboard. Dashboard is from recent Grafana version and is not working w/ Plutono ootb. Trying to get it to run. https://github.com/monitoringartist/opentelemetry-collector-monitoring could be a starting point for dashboard and alerts for the OTEL collector monitoring.

- [ ] Adding alerts to OpenTelemetry logs

**Comment by Kuckkuck** [comment]
Previous implementation: #339

**Comment by timojohlo** [comment]
follow-up on #435
