### ISSUE TITLE
[documentation] plugin documentation

### ISSUE THREAD

**Issue by artherd42** [cloudoperators/greenhouse-extensions#410]
### Description

As a Greenhouse user, I want to know in business language what I get from the various observability plugins to be able to assess whether it solves my problem.

### Objectives

- define a template for plugin documentation
- polish the readme's
- add a quick start guides
- add example architectures

### Acceptance criteria

- [ ] Plutono plugin
- [ ] OTEL collector plugin
- [ ] kube-monitoring plugin
- [ ] ...

**Comment by richardtief** [comment]
duplicate to https://github.com/cloudoperators/greenhouse-extensions/issues/356
