### ISSUE TITLE
[opentelemetry] Create umbrella chart for ccloud to pull in greenouse-extension/opentelemetry chart

### ISSUE THREAD

**Issue by Kuckkuck** [cloudoperators/greenhouse-extensions#411]
To move owners-info out of the greenhouse-extension/opentelemetry chart, we have to switch the ccloud open-telemetry repository in sapcc/helm-charts to an umbrella chart.

**Comment by Kuckkuck** [comment]
- Renamed pipeline and sapcc/helm-charts/system/open-telemetry to sapcc/helm-charts/system/opentelemetry
- Renamed pipeline from open-telemetry to opentelemetry
- switched pipelines branches back to main/master as this new helm-chart is just an umbrella chart
- images are build from main branch

**Comment by Kuckkuck** [comment]
pull request created (7101)[https://github.com/sapcc/helm-charts/pull/7101]

**Comment by timojohlo** [comment]
rolled out via pipeline
