### ISSUE TITLE
[opentelemetry] deployment to greenhouse is failing, because of opentelemetry vendor tests

### ISSUE THREAD

**Issue by Kuckkuck** [cloudoperators/greenhouse-extensions#412]
Deployment of OpenTelemetry is failing, after we have added our own chart testing. 
During deployment our tests are rolled out, but also the vendor own tests are executed, which are failing.

**Comment by timojohlo** [comment]
Should be fixed with https://github.com/cloudoperators/greenhouse-extensions/pull/428, thanks to @ibakshay
