### ISSUE TITLE
Check and alert on metric absence

### ISSUE THREAD

**Issue by artherd42** [cloudoperators/greenhouse-extensions#463]
### Priority

(Medium) I'm annoyed but I'll live

### Is your feature request related to a problem?

For proper alerting, the metrics that were used in the alert rule definitions in a `PrometheusRule` must exists. 

### Additional context.

Use the https://github.com/sapcc/absent-metrics-operator for checking and alerting on absent metrics.

**Comment by richardtief** [comment]
https://github.com/cloudoperators/greenhouse-extensions/issues/118
