### ISSUE TITLE
🐛 [BUG] - dev-env ui pods do not work as expected

### ISSUE THREAD

**Issue by uwe-mayer** [cloudoperators/greenhouse-extensions#47]
### Priority

(Medium) I'm annoyed but I'll live

### Description

Currently `greenhouse-ui` pod is not showing the expected UI on `http://localhost:3001/` within the `dev-env` setup as stated in the [Readme](https://github.com/cloudoperators/greenhouse-extensions/tree/main/dev-env#readme).
This will be fixed, once the serving of the greenhouse ui is refactored in greenhouse core. 

~~The respective issue will be linked from https://github.com/cloudoperators/greenhouse once it exits.~~

Issue tracking the new `greenhouse-ui` container: https://github.com/cloudoperators/greenhouse/issues/122

### Reproduction steps

```bash
./dev-env/ $ docker-compose up 
```

Check http://localhost:3001/ : It will not show any content

**Comment by IvoGoman** [comment]
@uwe-mayer we have a working Greenhouse UI in the dev-env since: https://github.com/cloudoperators/greenhouse-extensions/pull/104
Can we close this one and track the docker compose update to pull UI container images from GHCR in  https://github.com/cloudoperators/greenhouse/issues/122 ?
