### ISSUE TITLE
[opentelemetry] Simplify structure of helm-chart

### ISSUE THREAD

**Issue by timojohlo** [cloudoperators/greenhouse-extensions#484]
## Context 
The [opentelemetry directory](https://github.com/cloudoperators/greenhouse-extensions/tree/main/opentelemetry) currently consists of a overcomplicated structure with 
```

root:
	global:
	prometheusRules:
	owner-info:
	customLabels:
	opentelemetry-operator:
	openTelemetry:
	testFramework:
```

With some prometheus configuration in `openTelemetry.prometheus` the configurations for prometheus should be moved to one leaf and not required values can be removed (e.g. `owner-info`)

Plus: Getting rid of different keys in different files overwriting

**Comment by olandr** [comment]
Closed as per #518
