### ISSUE TITLE
[thanos] Long-term storage capabilities for Prometheus metrics

### ISSUE THREAD

**Issue by artherd42** [cloudoperators/greenhouse-extensions#77]
## Context

The kube-monitoring plugin's integrated Prometheus stores metrics on Kubernetes persistent volumes. This setup has some limitations, especially if the metrics data grows quickly and you want to keep the data long-term. [Thanos](https://github.com/thanos-io/thanos) extends this system with the object storage of your choice to store your metrics indefinitely. GCP, S3, Azure and Swift(Ceph) should be supported.

## Acceptance criteria

1. Enhance kube-monitoring plugin to store in an object store using Thanos
2. Configure downsampling of historical data
3. Seamlessly query metrics from Prometheus/Thanos

**Comment by viennaa** [comment]
Moved into #180 #181
